#ifndef _CONFIG_H_
#define _CONFIG_H_

#define PI 3.14159265358979323846

#define VENTANA_ANCHO 1000
#define VENTANA_ALTO 800

#define JUEGO_FPS 100

#define VIDAS 4
#define S_VIDAS "SHIP"
#define SEGUNDOS_RESPAWN 1
#define SEGUNDOS_INMUNIDAD 3

#define RADIO_ASTEROIDE 32

#define PTOS_GRANDE 20
#define PTOS_MEDIANO 50
#define PTOS_CHICO 100

#define CANT_AST_INICIAL 4

#define NAVE_ROTACION_PASO (PI/20)

#define NAVE_X_INICIAL (VENTANA_ANCHO/2)
#define NAVE_Y_INICIAL (VENTANA_ALTO/2)
#define NAVE_VX_INICIAL 0
#define NAVE_VY_INICIAL 0
#define NAVE_ANGULO_INICIAL 0
#define NAVE_POTENCIA_INICIAL 0
#define RADIO_NAVE 12 //numero magico

#endif // _CONFIG_H_

